import Head from 'next/head'
import AppContainer from '@/components/AppContainer'
import HomeComponent from '@/components/PageComponents/HomeComponent'


export default function Home() {
  return (
    <>
      <Head>
        <title>Mohit Sharma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppContainer>
      <HomeComponent />
      </AppContainer>
    </>
  )
}
